server:
  port: 7788

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: web
      client-secret: 123123
      user-authorization-uri: http://127.0.0.1:7777/oauth/authorize # 获取用户的授权码地址
      access-token-uri: http://127.0.0.1:7777/oauth/token # 获取访问令牌的地址
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: http://127.0.0.1:7777/oauth/check_token # 校验访问令牌是否有效的地址
